package ayman.issa.hostelworld.common.util

fun translateToFacility(id: String): FacilitiesEnum {
    return when (id.uppercase()) {
        "24HOURRECEPTION" -> FacilitiesEnum.TWENTYFOUR_HOUR_RECEPTION
        "24HOURSECURITY" -> FacilitiesEnum.TWENTYFOUR_HOUR_SECURITY
        else -> FacilitiesEnum.valueOf(id.uppercase())
    }
}

fun translateToFacilityCategory(id: String): FacilityCategoriesEnum {
    return FacilityCategoriesEnum.valueOf(id.uppercase())
}

enum class FacilityCategoriesEnum {
    FACILITYCATEGORYSERVICES,
    FACILITYCATEGORYENTERTAINMENT,
    FACILITYCATEGORYFOODANDDRINK,
    FACILITYCATEGORYFREE,
    FACILITYCATEGORYGENERAL,
}

enum class FacilitiesEnum {
    ADAPTORS,
    AIRCONDITIONING,
    AIRPORTTRANSFERS,
    ATM,
    BAR,
    BBQ,
    BICYCLEHIRE,
    BICYCLEPARKING,
    BOARDGAMES,
    BOOKEXCHANGE,
    BREAKFASTINCLUDED,
    BREAKFASTNOTINCLUDED,
    BUSINESSCENTRE,
    CABLETV,
    CAFE,
    CARDPHONES,
    CEILINGFAN,
    COMMONROOM,
    COOKER,
    COTSAVAILABLE,
    CURRENCYEXCHANGE,
    DISHWASHER,
    DRYER,
    DVDS,
    ELEVATOR,
    EXPRESSCHECKINOUT,
    FAXSERVICE,
    FLEXIBLENRR,
    FREEAIRPORTTRANSFERS,
    FREECITYMAPS,
    FREECITYTOUR,
    FREEINTERNETACCESS,
    FREEPARKING,
    FREEWIFI,
    FRIDGEFREEZER,
    FUSBALL,
    GAMESROOM,
    HAIRDRYERS,
    HAIRDRYERSFORHIRE,
    HOTSHOWERS,
    HOUSEKEEPING,
    INTERNETACCESS,
    IRONIRONINGBOARD,
    JOBSBOARD,
    KEYCARDACCESS,
    KITCHEN,
    LATECHECKOUT,
    LAUNDRYFACILITIES,
    LINENINCLUDED,
    LOCKERS,
    LUGGAGESTORAGE,
    MEALSAVAILABLE,
    MEETINGROOM,
    MICROWAVE,
    MINIBAR,
    MINISUPERMARKET,
    OUTDOORTERRACE,
    PARKING,
    PLAYSTATION,
    POOLTABLE,
    POSTALSERVICE,
    READINGLIGHT,
    RECEPTIONLIMITEDHOURS,
    RESTAURANT,
    SAFEDEPOSITBOX,
    SANITISATIONBADGE,
    SHUTTLEBUS,
    TEACOFFEEMAKINGFACILITIES,
    TOURSTRAVELDESK,
    TOWELSFORHIRE,
    TOWELSINCLUDED,
    TOWELSNOTINCLUDED,
    UTENSILS,
    VENDINGMACHINES,
    WAKEUPCALLS,
    WASHINGMACHINE,
    WHEELCHAIRACCESSIBLE,
    WIFI,
    TWENTYFOUR_HOUR_RECEPTION,
    TWENTYFOUR_HOUR_SECURITY
}